### ISSUE TITLE
Downloading clips does not work

### ISSUE THREAD

**Issue by jonathanjsimon** [koush/nvr.scrypted.app#18] opened 2023-06-28 15:06 UTC
When I create clip in the camera view, the file that is downloaded is ~1.25kb and contains no video data. I've tried this on my Android phone as well as my Linux desktop. Same as if I visit the camera instance in config and download clips from the history there. The video file is empty aside from mp4 header info.

Current docker image running scrypted 0.39.0. Cameras are all Reolink RLC-810As. The historical rtsp data is definitely available in storage as stored by Scrypted NVR.

https://github.com/koush/scrypted/assets/1076597/663c8be0-7b12-4c1d-b630-5d562e601074

Is there any additional info needed?

**Comment by jonathanjsimon** [comment] 2023-06-28 16:30
Brave in all cases

**Comment by koush** [comment] 2023-06-28 16:32
Can you try Chrome to see if it's a browser specific issue?

**Comment by jonathanjsimon** [comment] 2023-06-28 17:16
Understood. I have tried Chrome and Firefox without success.

**Comment by koush** [comment] 2023-06-28 17:21
Can you attach a console log from the camera after attempting to export?

**Comment by jonathanjsimon** [comment] 2023-06-28 17:46
Separate instances of the problem but here are logs from the browser and the docker container

[javascript console.log](https://github.com/koush/nvr.scrypted.app/files/11898635/javascript.console.log)
[docker.log](https://github.com/koush/nvr.scrypted.app/files/11898636/docker.log)

**Comment by koush** [comment] 2023-06-28 18:31
Ok I see the export issue now. Incidentally may want to reload the NVR Plugin. There seems to be something stuck on a camera that you added then deleted?

**Comment by koush** [comment] 2023-06-28 18:38
Should be fixed with the plugin update. Please confirm.

**Comment by koush** [comment] 2023-06-28 19:43
Please provide another log of the recording download

**Comment by jonathanjsimon** [comment] 2023-06-29 00:13
[scrypted_logs.txt](https://github.com/koush/nvr.scrypted.app/files/11900777/scrypted_logs.txt)


I think the interesting bits start around `2023-06-29T00:00:55.435474214Z`

Having done it at home instead of over the internet, my experience is slightly different. The selection to download was about 5 seconds of video. It streamed over 800mb to my computer locally as a download before I bailed on it. The logs were full of packet loss entries and lowest resolution entries.

**Comment by koush** [comment] 2023-06-29 01:26
```
2023-06-29T00:01:16.148099525Z [Garage RLC-810A] Input #0, rtsp, from 'rtsp://127.0.0.1:43397/10237e8a11d29acd':
2023-06-29T00:01:16.148166627Z   Duration: N/A, start: 0.000000, bitrate: N/A
2023-06-29T00:01:16.148176847Z   Stream #0:0: Video: hevc (Main), yuv420p(tv), 3840x2160, 24.92 tbr, 90k tbn, 90k tbc
2023-06-29T00:01:16.148184857Z   Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
2023-06-29T00:01:16.148194287Z Output #0, mp4, to 'pipe:3':
2023-06-29T00:01:16.148232268Z   Metadata:
2023-06-29T00:01:16.148240328Z     encoder         : Lavf58.76.100
2023-06-29T00:01:16.148250148Z   Stream #0:0: Video: hevc (Main) (hev1 / 0x31766568), yuv420p(tv), 3840x2160, q=2-31, 24.92 tbr, 90k tbn, 90k tbc
2023-06-29T00:01:16.148257969Z   Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, mono, fltp
2023-06-29T00:01:16.148267359Z Stream mapping:
```

Oh, just noticed you're using HEVC/h265. Please set your cameras to h264. There's a codec guide you can follow. You may need to use the reolink plugin rather than ONVIF. Not sure what Reolink exposes via ONVIF. It may only send the h265 stream.

**Comment by koush** [comment] 2023-06-29 01:37
Have confirmed the issue where mp4 export on hevc stream is being unecessarily transcoded. Fixing this, but NVR codec guide recommends using h264 since that is the only supported browser codec (otherwise it transcodes).
As mentioned, need to maybe use reolink plugin to do that. Will follow up again once publish the hevc export issue shortly.

**Closed** 2023-06-29 01:46 UTC

**Comment by jonathanjsimon** [comment] 2023-06-29 02:12
Unfortunately, the RLC-810A only supports h265 and the Reolink plugin seems to only show snapshots (maybe as a result?). I'll reproduce tomorrow and get you the logs. If I have to transcode, that's fine, I have the hardware for it.

https://reolink.com/product/rlc-810a/#specifications

**Comment by koush** [comment] 2023-06-29 02:39
Might be worth checking this out. https://www.reddit.com/r/homeassistant/comments/sopd9a/hidden_h264_stream_in_reolink_rlc_810a_probably/

It supportsedly support h264 if you lower the resolution. You'll have a much better experience with h264 due to regular keyframes and reduced system load. Let me know what you discover.
